language: objective-c
osx_image: xcode7.3
xcode_project: OnboardingControllerExamples.xcodeproj
xcode_scheme: OnboardingControllerExamples
xcode_sdk: iphonesimulator9.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6s" SDK=iphonesimulator9.3
branches:
  only:
    - master
script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - xcodebuild -project OnboardingControllerExamples.xcodeproj -scheme OnboardingControllerExamples -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO -sdk "$SDK" build
    - xcodebuild -project OnboardingControllerExamples.xcodeproj -scheme OnboardingControllerExamples -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO -sdk "$SDK" test
