branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode7.3
script:
    - xcodebuild clean build test -project OnboardingControllerExamples.xcodeproj -scheme OnboardingControllerExamples -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'
