branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode7.2
script:
  - xctool -project OnboardingControllerExamples.xcodeproj -sdk iphonesimulator -scheme OnboardingControllerExamples build